#include "hardware.h"

const ServoTable_t Neutral[]=
{ { TIM2_SERVO_SCALE(0),TIM2_SERVO_SCALE(0),1 },
	{ 0,0,0}
};

/*
const ServoTable_t Forward_Tbl[]=
{
	{ TIM2_SERVO_SCALE(0),TIM2_SERVO_SCALE(30),SERVO_WAIT },
	{ TIM2_SERVO_SCALE(30),TIM2_SERVO_SCALE(90),SERVO_FAST },
	{	TIM2_SERVO_SCALE(90),TIM2_SERVO_SCALE(90),SERVO_WAIT },
	{ TIM2_SERVO_SCALE(90),TIM2_SERVO_SCALE(0),SERVO_ROW2},
	{ TIM2_SERVO_SCALE(0),TIM2_SERVO_SCALE(0),20 },
	{ TIM2_SERVO_SCALE(0),TIM2_SERVO_SCALE(-30),10},
	{ TIM2_SERVO_SCALE(-30),TIM2_SERVO_SCALE(-90),SERVO_FAST},
	{ TIM2_SERVO_SCALE(-90),TIM2_SERVO_SCALE(-90),SERVO_WAIT},
	{ TIM2_SERVO_SCALE(-90),TIM2_SERVO_SCALE(0),SERVO_ROW},	
	{ END_TABLE,END_TABLE,0},
};
*/

const ServoTable_t Forward_Tbl[]=
{
	{ TIM2_SERVO_SCALE(0),TIM2_SERVO_SCALE(90),SERVO_SLOW},
	{ TIM2_SERVO_SCALE(90),TIM2_SERVO_SCALE(0),SERVO_FAST},
	{ TIM2_SERVO_SCALE(0),TIM2_SERVO_SCALE(0),SERVO_WAIT},	
	{ TIM2_SERVO_SCALE(0),TIM2_SERVO_SCALE(-90),SERVO_SLOW},
	{ TIM2_SERVO_SCALE(-90),TIM2_SERVO_SCALE(0),SERVO_FAST},
	{ TIM2_SERVO_SCALE(0),TIM2_SERVO_SCALE(0),SERVO_WAIT},	
	{ END_TABLE,END_TABLE,0},
};



/*
const ServoTable_t Forward_Tbl[]=
{	
  { TIM2_SERVO_SCALE(0),TIM2_SERVO_SCALE(-90),SERVO_ROW},	
	{ TIM2_SERVO_SCALE(-90),TIM2_SERVO_SCALE(0),SERVO_ROW},
	{ TIM2_SERVO_SCALE(0),TIM2_SERVO_SCALE(0),SERVO_LONGWAIT},	
	{ TIM2_SERVO_SCALE(0),TIM2_SERVO_SCALE(90),SERVO_ROW},
	{ TIM2_SERVO_SCALE(90),TIM2_SERVO_SCALE(0),SERVO_ROW},
	{ TIM2_SERVO_SCALE(0),TIM2_SERVO_SCALE(0),SERVO_LONGWAIT},
	{ END_TABLE,END_TABLE,0},
};

*/

const ServoTable_t Left_Tbl[]=
{
	{ TIM2_SERVO_SCALE(0),TIM2_SERVO_SCALE(-45),SERVO_ROW},
	{ TIM2_SERVO_SCALE(-45),TIM2_SERVO_SCALE(-45),SERVO_LONGWAIT},	
	{ TIM2_SERVO_SCALE(-45),TIM2_SERVO_SCALE(-90),SERVO_ROW},	
	{ TIM2_SERVO_SCALE(-90),TIM2_SERVO_SCALE(0),SERVO_ROW2},
	{ END_TABLE,END_TABLE,0},
};

const ServoTable_t Right_Tbl[]=
{
	{ TIM2_SERVO_SCALE(0),TIM2_SERVO_SCALE(45),SERVO_ROW},
	{ TIM2_SERVO_SCALE(45),TIM2_SERVO_SCALE(45),SERVO_LONGWAIT},	
	{ TIM2_SERVO_SCALE(45),TIM2_SERVO_SCALE(90),SERVO_ROW},	
	{ TIM2_SERVO_SCALE(90),TIM2_SERVO_SCALE(0),SERVO_ROW2},
	{ END_TABLE,END_TABLE,0},
};


const ServoTable_t Reverse_Tbl[]=
{
	{ TIM2_SERVO_SCALE(0),TIM2_SERVO_SCALE(90),SERVO_SLOW },
	{ TIM2_SERVO_SCALE(90),TIM2_SERVO_SCALE(30),SERVO_FAST},
  { TIM2_SERVO_SCALE(30),TIM2_SERVO_SCALE(30),SERVO_WAIT},
	{	TIM2_SERVO_SCALE(30),TIM2_SERVO_SCALE(-90),SERVO_SLOW },
	{ TIM2_SERVO_SCALE(-90),TIM2_SERVO_SCALE(-30),SERVO_FAST},
	{ TIM2_SERVO_SCALE(-30),TIM2_SERVO_SCALE(-30),SERVO_WAIT},
	{ TIM2_SERVO_SCALE(-30),TIM2_SERVO_SCALE(0),SERVO_SLOW },	
	{ END_TABLE,END_TABLE,0},
};

void main(void)
{
	Init_TIM2();
	// Turn on interrupts
	rim();
	
	ServoStep.Table = Forward_Tbl;
	while (1);
}
